// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ouxcwjehkkpenqzolwdc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91eGN3amVoa2twZW5xem9sd2RjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MjgwODMsImV4cCI6MjA1NzUwNDA4M30.oKX9ydXcugnnQzGOFrEPH5c3rYSZ2TTWgou3ulwIFE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);